name: Publish Docker Images to Harbor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Log in to Harbor registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        registry: ${{ secrets.HARBOR_REGISTRY_URL }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

  # Build Image 1 with OCI LABEL (already hardcoded in Dockerfile)
    - name: Build Image 1
      run: |
        docker build -f .github/workflows/Dockerfile -t ${{ secrets.HARBOR_REGISTRY_URL }}/test-demo/image1:v1 .
        docker push ${{ secrets.HARBOR_REGISTRY_URL }}/test-demo/image1:v1  # Fixed the issue here

    # Build Image 2 with Provenance (Attestation) and Push to Harbor
    - name: Build Image 2 with Provenance (Attestation)
      run: |
        docker buildx build --provenance=true -f .github/workflows/Dockerfile -t ${{ secrets.HARBOR_REGISTRY_URL }}/test-demo/image2:v2 --push .
    - name: Logout from Harbor
      run: docker logout ${{ secrets.HARBOR_REGISTRY_URL }}
